-- Migration 026: Self-healing import recipes + import telemetry
-- ----------------------------------------------------------------
-- import_recipes stores per-domain extraction recipes generated by
-- the LLM fallback when deterministic extraction comes back weak.
-- Same JSONB shape as site-registry.json selectors, so the existing
-- cheerio extractor consumes them directly. Manual registry recipes
-- always take precedence over generated ones.
--
-- Regeneration is lazy: when a stored recipe stops producing good
-- extractions (site redesign), the next import regenerates it. No
-- cron needed. confidence=0 rows act as a negative cache so dead
-- domains (JS-only shells) don't re-trigger LLM calls on every hit.
--
-- import_logs records one row per import attempt so failing domains
-- can be identified from real traffic instead of guesswork.

CREATE TABLE IF NOT EXISTS import_recipes (
  domain       VARCHAR(255) PRIMARY KEY,
  recipe       JSONB NOT NULL,
  confidence   NUMERIC(4, 2) DEFAULT 0,
  generations  INTEGER DEFAULT 1,
  created_at   TIMESTAMPTZ DEFAULT now(),
  updated_at   TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS import_logs (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  domain        VARCHAR(255) NOT NULL,
  url           TEXT NOT NULL,
  success       BOOLEAN NOT NULL,
  confidence    NUMERIC(4, 2),
  fields_found  TEXT[],
  body_chars    INTEGER DEFAULT 0,
  recipe_source VARCHAR(16),          -- registry | generated | none
  fetch_error   TEXT,
  created_at    TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_import_logs_domain ON import_logs (domain, created_at DESC);

COMMENT ON TABLE import_recipes IS 'LLM-generated per-domain extraction recipes (self-healing)';
COMMENT ON TABLE import_logs IS 'Per-import telemetry: which domains succeed/fail and why';
