import { readFile, writeFile, copyFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(scriptDirectory, "../../..");
const packageRoot = path.resolve(scriptDirectory, "..");
const sourceDirectory = path.join(packageRoot, "src");
const manifestsDirectory = path.join(packageRoot, "manifests");
const checkOnly = process.argv.includes("--check");

const browserTargets = ["chrome", "firefox", "safari"];
const sharedFiles = [
  "api-client.js",
  "background.js",
  "content.css",
  "content.js",
  "popup.html",
  "popup.js",
  "icon16.png",
  "icon16-affirmed.png",
  "icon16-corrected.png",
  "icon16-pending.png",
  "icon48.png",
  "icon48-affirmed.png",
  "icon48-corrected.png",
  "icon48-pending.png",
  "icon128.png",
  "icon128-affirmed.png",
  "icon128-corrected.png",
  "icon128-pending.png",
];

async function assertMatches(source, destination) {
  const [expected, actual] = await Promise.all([
    readFile(source),
    readFile(destination).catch(() => null),
  ]);
  if (!actual || !expected.equals(actual)) {
    throw new Error(`Generated file is stale: ${path.relative(repositoryRoot, destination)}`);
  }
}

async function copyOrCheck(source, destination) {
  if (checkOnly) {
    await assertMatches(source, destination);
    return;
  }
  await mkdir(path.dirname(destination), { recursive: true });
  await copyFile(source, destination);
}

async function buildBrowserTargets() {
  for (const browser of browserTargets) {
    const destinationDirectory = path.join(repositoryRoot, "extensions", browser);
    for (const filename of sharedFiles) {
      await copyOrCheck(
        path.join(sourceDirectory, filename),
        path.join(destinationDirectory, filename),
      );
    }
    await copyOrCheck(
      path.join(manifestsDirectory, `${browser}.json`),
      path.join(destinationDirectory, "manifest.json"),
    );
  }
}

async function buildMobileModule() {
  const [adapterTemplate, contentScript, contentCss] = await Promise.all([
    readFile(path.join(packageRoot, "adapters", "webview.js"), "utf8"),
    readFile(path.join(sourceDirectory, "content.js"), "utf8"),
    readFile(path.join(sourceDirectory, "content.css"), "utf8"),
  ]);

  const iconFiles = sharedFiles.filter((filename) => filename.endsWith(".png"));
  const iconEntries = await Promise.all(iconFiles.map(async (filename) => {
    const bytes = await readFile(path.join(sourceDirectory, filename));
    return [filename, `data:image/png;base64,${bytes.toString("base64")}`];
  }));
  const iconMap = Object.fromEntries(iconEntries);
  const adapter = adapterTemplate.replace(
    "__TA_MOBILE_ICON_MAP__",
    JSON.stringify(iconMap),
  );
  const mobileScript = `${adapter}\n\n${contentScript}`;
  const generated = [
    "/* This file is generated by packages/trust-overlay/scripts/build.mjs. */",
    "/* Edit packages/trust-overlay instead of changing this file directly. */",
    `export const CONTENT_SCRIPT: string = ${JSON.stringify(mobileScript)};`,
    `export const INJECTED_CSS: string = ${JSON.stringify(contentCss)};`,
    "",
  ].join("\n");

  const destination = path.join(
    repositoryRoot,
    "apps",
    "mobile",
    "src",
    "generated",
    "trustOverlay.generated.ts",
  );

  if (checkOnly) {
    const current = await readFile(destination, "utf8").catch(() => null);
    if (current !== generated) {
      throw new Error(`Generated file is stale: ${path.relative(repositoryRoot, destination)}`);
    }
    return;
  }

  await mkdir(path.dirname(destination), { recursive: true });
  await writeFile(destination, generated, "utf8");
}

await buildBrowserTargets();
await buildMobileModule();
console.log(checkOnly ? "Shared overlay outputs are current." : "Built browser and mobile overlay outputs.");
