import { W } from "../lib/scoring";

export default function RulesScreen() {
  const S = ({ children }) => <h3 style={{ fontFamily: "var(--serif)", fontSize: 17, marginBottom: 6, marginTop: 20 }}>{children}</h3>;
  return (
    <div><div className="ta-section-rule" /><h2 className="ta-section-head">Rules & Policies</h2>
      <div style={{ padding: 12, background: "#FFFBEB", border: "1.5px solid #B45309", borderRadius: 8, marginBottom: 16, fontSize: 12, color: "#92400E", lineHeight: 1.6 }}>
        <strong>⚠ BETA:</strong> The Trust Assembly is in early beta. Features may change, data may be reset, and the system is under active development. <strong>Do not enter sensitive personal information.</strong> Use a pseudonym if you prefer. By participating you acknowledge this is an experimental platform.
      </div>
      <div className="ta-card" style={{ fontSize: 13, lineHeight: 1.7, color: "#1E293B" }}>
        <S>I. Purpose</S><p>Truth emerges through structured adversarial review. The only way to build reputation is honesty. The cost of lying is severe enough to make deception irrational.</p>
        <S>II. Assemblies & Enrollment</S><p>Citizens may join up to 12 Assemblies simultaneously. Every citizen is permanently enrolled in The General Public. <strong>Tribal Rule (1–50 members):</strong> The founder personally approves or rejects every application. This power expires at 51 members. <strong>Open enrollment (51–99):</strong> Anyone can join directly. <strong>Sponsor required (100+):</strong> 100–999: 1 sponsor. 1,000–9,999: 2 sponsors. 10,000+: 3 sponsors. <strong>Who can sponsor?</strong> Members who have submitted at least one correction can sponsor immediately. Review-only members need 10+ completed reviews and 30 days of membership — a higher bar reflecting that they haven't put their own reputation on the line through submissions. All applications include a written reason and optional link. Republic-style self-governance activates with 1,000,000+ citizens.</p>
        <S>II-A. Deliberate Deception Penalty</S><p>A finding of deliberate deception carries a <strong>1-year penalty</strong>: all voting rights suspended, sponsorship rights suspended, assembly creation suspended. The penalty is visible on the citizen's public record. The citizen may still submit corrections during the penalty period — rebuilding trust requires continued honest participation.</p>
        <S>III. Submissions</S><p>Citizens submit <strong>corrections</strong> (headline is misleading — propose a replacement) or <strong>affirmations</strong> (headline is accurate — provide supporting evidence). Both types are reviewed by juries on the same criteria. Author name is captured for future writer accountability ratings. Optional: up to 20 in-line article edits (each voted on independently by jurors), Vault entries (Standing Corrections, Arguments, Foundational Beliefs, and Translations).</p>
        <S>IV. Jury Review</S><p>Jury size scales with Assembly membership: 5–20 members → 3 jurors; 21–50 → 5; 51–100 → 7; 101–999 → 9; 1,000–9,999 → 11; 10,000+ → 13. Simple majority decides (e.g. 2-of-3, 3-of-5, 4-of-7). Rules escalate: 100+ members: no repeat reviewer, diversity attempt (gender and region — political affiliation will be added as a diversity factor in the future). 500+: join-date filter. 1,000+: 24h cooldown. Recusal always available. <strong>Deeper bench:</strong> The system draws 2× the needed jury size. All drawn members see the review as an opportunity. First to click "Accept" are seated — making jury service civic volunteerism, not conscription. If the jury is already full when someone clicks, they receive a notification and are thanked for their willingness. <strong>6-hour window:</strong> Once you accept a seat, you have 6 hours to complete your review. If you don't finish, your seat opens to another juror — no penalty, life happens. Unaccepted pool seats also rotate after 6 hours, with a second 6-hour round before the system reduces jury size as a last resort. <strong>Jury Score:</strong> Every juror builds a visible Jury Score tracking: consensus alignment (how often you vote with the final outcome — 50–85% is the healthy range), overturn rate (how often juries you served on were overturned by dispute), and accusation accuracy (when you flagged deception, how often the jury agreed). Jury Score is visible on your profile. At launch, Jury Score will not be used to select jurors — selection remains random — but it is tracked from day one for future versions of the system. Approved corrections advance to cross-group review.</p>
        <S>V. Cross-Group Consensus</S><p>Cross-group jury size scales with ecosystem diversity — the number of qualifying Assemblies (100+ members each). 5–7 assemblies → 3 jurors; 8–12 → 5; 13–20 → 7; 21–50 → 9; 51–100 → 11; 100+ → 13. Requires a minimum of 5 qualifying Assemblies before activation. <strong>Jurors must not be members of the originating Assembly.</strong> No two jurors may share more than 2 non-General Public Assembly memberships — this overlap constraint guarantees genuinely independent perspectives. The General Public is excluded from overlap counting since all citizens share it. If the overlap constraint cannot seat the full jury, it falls back to the largest jury achievable (minimum 3). Surviving both in-group and cross-group review = Consensus — the highest trust signal.</p>
        <S>VI. Intra-Assembly Disputes</S><p>At 100+ members, citizens may dispute other members' content. A minimum of 3 uninvolved jurors, same rules. Winners get significant reputation gains. Losers lose reputation, severity depends on Deliberate Deception Finding.</p>
        <S>VI-A. Disputes & The Cassandra Rule</S><p>A successful dispute earns <strong>+{W.disputeWin} points</strong> for catching an error. A failed dispute adds to your drag (same coefficient as a regular loss, diminishing via √). <strong>The Cassandra Rule</strong> is a separate, higher-stakes mechanic: if your correction is disputed and the dispute is upheld — meaning you were found wrong — but you refuse to concede because you believe you're right, and you are later vindicated through a vindication review, you earn a massive <strong>additive bonus</strong> that scales with both the importance of the correction and the number of rejections you weathered. Named for the prophet nobody believed. The full Cassandra vindication path is being built; at launch, dispute wins earn +{W.disputeWin} points.</p>
        <S>VII. Deliberate Deception Findings</S><p>During any review, jurors cast a secret ballot certifying the submission is a deliberate lie, gross misrepresentation, or intentional omission. Simple majority triggers a Finding. Penalty: +{W.lieDrag} drag per lie (linear, bypasses the √ diminishing curve that softens regular losses). Juror identity never revealed to submitter.</p>
        <S>VIII. Retractions</S><p>Citizens may voluntarily retract. Lie retraction within 1 week: recovers 50% of penalty. Wrong retraction within 1 week: recovers 90%. Each subsequent week removes 10% of amelioration until zero. Flat subtraction, not exponential.</p>
        <S>IX. Assembly Reputation</S><p>Each Assembly's Trust Score is based exclusively on cross-group review outcomes — the percentage of internally approved corrections that survive external review, weighted by combined jury rigor (internal jury size + cross-group jury size). There is <strong>no time decay</strong>; the full historical record is permanent. The score requires a minimum of 20 completed cross-group reviews before it displays. <strong>Cross-group deception findings</strong> carry a severe penalty against the Assembly's reputation. The <strong>Dispute Index</strong> tracks successful disputes filed by the Assembly's members against other Assemblies — measuring how sharp the community's eyes are.</p>
        <S>IX-A. Assembly Concessions</S><p>When an Assembly's correction is rejected by cross-group review, any member may propose the Assembly officially concede. A <strong>super jury</strong> (approximately double normal jury size, minimum 7) decides by simple majority. One concession per rolling 7-day window gets 100% recovery (no loss). Additional concessions in the same week recover 90%. After 1 week: 90%. After 2 weeks: 50%. After 1 month: 25%. After 3 months: 5%. The dispute winner retains their full reward regardless of whether the Assembly concedes — the Assembly does not share in that reward. A conceding Assembly is rewarded for humility; a stubborn Assembly pays the permanent cost.</p>
        <S>X. Trusted Contributor</S><p><strong>10 consecutive approved corrections</strong> in a single Assembly earns Trusted Contributor status. Submissions skip in-group jury and are immediately approved — but remain <strong>disputable</strong> by any member. Status is per-Assembly, not global. Any rejection via dispute revokes the status instantly. A Deliberate Deception Finding also revokes it. The status is publicly visible on all submission cards.</p>
        <S>X-A. Digital Intelligences</S><p>AI agents may register as Digital Intelligences (DIs). Each DI must be linked to an accountable human partner. <strong>The human partner receives all scoring</strong> from DI submissions, including deception drag penalties. DIs cannot vote, serve on juries, or sponsor members. Daily submissions limited to half the Assembly's membership (max 100). All DI submissions require partner pre-approval before entering jury review. All DI submissions are permanently flagged. If the human partner receives a Deception penalty, all linked DIs are suspended for the duration.</p>
        <S>XI. Scoring</S><p>Trust Score (unbounded, higher is better). Formula: √(Points) × Quality / Drag + Cassandra Bonus. Points: wins + dispute wins×2 + streak bonus (1 per 3 consecutive wins). Volume has diminishing returns (√). Quality: (avgNews + avgFun)/10, capped at 1.6, raised to power 1.5 — trivial work penalized, important work amplified. Drag: 1 + √(losses×2 + failed disputes×2) + lies×3. Lies bypass the square root — each one adds 3.0 directly. Cassandra vindication: additive bonus, scales with impact × persistence (coming soon). All weights are community-votable in future elections. Profiles: Oracle, Diligent Reporter, Raconteur, Archivist, Demagogue, Overreacher, Court Jester, Apprentice.</p>
        <S>XI-A. Badges</S><p>Badges are earned automatically through participation and appear on your public profile. Each badge earned adds +1 to your Trust Score. Badge categories: <strong>Submission milestones</strong> (1, 10, 100, 1K, 10K, 100K, 1M). <strong>Trusted Contributor</strong> (earned trusted status in any Assembly). <strong>Assembly Creator</strong> (founded an Assembly). <strong>Assembly Member</strong> (joined beyond The General Public). <strong>Founder Milestones</strong> (Assembly reaches 5, 21, 51, 101, 1K, or 10K members). <strong>Early Adopter</strong> (first 100 or first 1,000 citizens). Badges are tiered (bronze through legendary) based on difficulty. They cannot be purchased, transferred, or manually assigned — only earned.</p>
        <S>XII. The Vaults</S><p>Standing Corrections (reusable verified facts). Argument Vault (fundamental arguments for reuse). Foundational Belief Vault (core axioms — starting premises, not claims of fact). Translation Vault (plain-language replacements for jargon, spin, propaganda, and euphemisms — categories: Clarity, Anti-Propaganda, Euphemism, Satirical). Approved translations are applied automatically by the browser extension across all articles.</p>
        <S>XIII. Legal</S><p>Citizens bear sole responsibility for all content. The Trust Assembly makes no representations regarding accuracy. Jury decisions reflect peer consensus, not institutional endorsement.</p>
      </div>
    </div>
  );
}
